### ISSUE TITLE
Please instruction help

### ISSUE THREAD

**Issue by Ergus** [ComputerNerd/RawCamera-data-converter#1]
Hi I am using this program to see the images from ov7670. I already build and upload the other project: ov7670-no-ram-arduino-uno to my arduino uno. And my "cat /dev/ttyACM0" prints undeadable data (so it is working). But I don't understand how to use this program  to see the image. (it compiles without any issue)
I tried: ./convert -f /dev/ttyACM0 cause the instructions with -h is not understandable at all; at least for me. 
I only get: Error while saving PNG.
What I am supposed to do for reading the information from the arduino and convert it to something useful. 
I see there have not being activity in this repo un 4 years, but I hope you can give a hint. I can contribute to the project one I made it work for the first time.

**Comment by ComputerNerd** [comment]
It only supports reading from files.
